"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import sys

from setuptools import setup

sys.setrecursionlimit(5000)

APP = ['Program.py']
DATA_FILES = ['*.qml', '*.sql']
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
